// Build script — bundles 00→03 into a single code.js with menu commands.
// Run: node build.js   (from figma-plugin/helix/)
// Result: import manifest.json once in Figma, then run parts from the
// plugin submenu or "Run ALL" — no more pasting scripts one by one.

const fs = require("fs");
const path = require("path");

const parts = [
  ["part00", "00-variables.js"],
  ["part01", "01-foundation.js"],
  ["part02", "02-components.js"],
  ["part02b", "02b-components-extra.js"],
  ["part03", "03-screens.js"],
];

let out = `// ============================================================
// HELIX CRYPTO UI KIT — bundled plugin (generated by build.js)
// Do not edit by hand: edit 00→03 sources and re-run  node build.js
// Menu: Run ALL, or each part separately (see manifest.json "menu")
// ============================================================

const __done = (msg) => { figma.notify(String(msg), { timeout: 4000 }); console.log(msg); };

`;

for (const [fnName, file] of parts) {
  let src = fs.readFileSync(path.join(__dirname, file), "utf8");
  const open = src.indexOf("(async () => {");
  const close = src.lastIndexOf("})();");
  if (open === -1 || close === -1) throw new Error(`IIFE wrapper not found in ${file}`);
  let body = src.slice(open + "(async () => {".length, close);
  // parts must not terminate the plugin mid-run — notify instead
  body = body.replace(/figma\.closePlugin\(/g, "__done(");
  out += `// ─────────── ${file} ───────────\nasync function ${fnName}() {${body}}\n\n`;
}

out += `(async () => {
  const registry = { s00: part00, s01: part01, s02: part02, s02b: part02b, s03: part03 };
  const order = ["s00", "s01", "s02", "s02b", "s03"];
  if (!figma.command || figma.command === "all") {
    // isolate failures so one bad part never blocks the rest
    const fails = [];
    for (const key of order) {
      try { await registry[key](); }
      catch (e) { fails.push(key + ": " + (e && e.message ? e.message : e)); }
    }
    figma.closePlugin(fails.length
      ? "⚠️ Helix generated with errors — " + fails.join(" · ")
      : "✅ Helix Crypto UI Kit — all parts generated");
  } else {
    try {
      await registry[figma.command]();
      figma.closePlugin("✅ Helix part done: " + figma.command);
    } catch (e) {
      figma.closePlugin("❌ " + (e && e.message ? e.message : e));
    }
  }
})();
`;

fs.writeFileSync(path.join(__dirname, "code.js"), out);
console.log(`code.js written (${(out.length / 1024).toFixed(0)} KB)`);
